version: '1.0'

services:
  yarpapi:
    build:
      context: .
      dockerfile: YARP_Api/Dockerfile
      args:
        BUILD_CONFIGURATION: ${BUILD_CONFIGURATION}
        ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
    ports:
      - "5286:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
    develop:
      watch:
        - action: rebuild
          path: ./YARP_Api
          target: /src/YARP_Api
  yarpreverseproxy:
    build:
      context: .
      dockerfile: YARP_ReverseProxy/Dockerfile
      args:
        BUILD_CONFIGURATION: ${BUILD_CONFIGURATION}
        ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
    ports:
      - "5044:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
    develop:
      watch:
        - action: rebuild
          path: ./YARP_ReverseProxy
          target: /src/YARP_ReverseProxy
          
  yarpclient:
    build:
      context: ./YARP_Client/yarp-app
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    develop:
      watch:
        - action: rebuild
          path: ./YARP_Client
          target: /app
    